export function buildOutputContractPrompt() {
  return [
    "Final answer contract:",
    "Return only the final answer for the traveler. Do not include reasoning, analysis, self-checks, or comments about these instructions.",
    "Use the Stable output template as the single source of truth for headings.",
    "Do not exceed three top-level headings.",
    "Make the answer short, precise, and easy to scan. Remove background that does not change what the traveler should do.",
    "Markdown tables are allowed only for short structured comparisons such as Useful Chinese phrases, app choices, or transport options. Keep table headers short and use 2-5 rows.",
    "Do not use bare separators such as ---, ***, or ___.",
    "Do not produce broken Markdown, unfinished lists, or mixed heading structures.",
    "For list items, prefer Short title: detail. Keep the title short enough to render as a bold label.",
    "Do not give generic sightseeing advice without the execution details a foreign visitor needs.",
    "Itinerary answers must prioritize route order, time allocation, transport method, booking risk, and one backup option.",
    "For one-day itineraries, every Do This item must use Short title: clear action format. Do not put nested bullets, repeated 1. items, or substeps under Morning, Lunch, Afternoon, or Evening.",
    "For 2-day or longer itineraries, use ### Day N: Short Theme sections under ## Do This, and restart Morning/Afternoon/Evening numbering inside each day.",
    "Payment answers must prioritize whether the user can pay, what to set up, what can fail, and the backup payment. Avoid exact cash, ATM withdrawal, fee, or exchange-rate amounts unless the user asks.",
    "Payment failure answers must stay under 450 words, include a connection or mobile data check, and include one backup payment path.",
    "Do not advise travelers to leave passports, phones, or valuables as collateral for unpaid bills.",
    "Do not cite cash law, legal tender rules, or absolute merchant obligations; tell the traveler to ask staff or a manager instead.",
    "Transport answers must prioritize where to go, how to board or meet the driver, how to pay, and what to show staff.",
    "Tickets answers must prioritize whether reservation is needed, passport requirements, sold-out or closure risk, and one alternative.",
    "For closure-day ticket answers, include a fallback date, nearby alternative, or backup plan if the venue is closed.",
    "Emergency answers must start with the immediate safe action, then who to contact and what short Chinese text to show.",
    "Language-card answers must stay compact: provide the Chinese card first, then at most 1-3 short usage steps. Do not include paragraph-length pinyin blocks.",
    "If the user asks to continue the previous answer, continue from where the prior answer stopped. Do not repeat the full opening or restart the whole answer.",
    "If the user selected a quick-question subtopic, focus only on that specific question. Do not expand into a full guide for the whole category unless the user asks for it.",
    "If the user's question is vague, give the safest default answer and end with one concise request for the missing city, date, budget, or situation.",
  ].join("\n");
}
